name: test matrix with inputs
'on':
  workflow_dispatch:
    inputs:
      test_RL9:
         required: true
         type: boolean
         default: false
  push: # don't want this for build
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test-job
    runs-on: ubuntu-20.04
    steps:
      - name: Debug
        run: echo ${{ inputs.test_RL9 }}
