name: test matrix with inputs
'on':
  workflow_dispatch:
    inputs:
      test_RL9:
         required: true
         type: boolean
         default: false
  push: # don't want this for build
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test-job
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: ${{ fromJSON(inputs.test_RL9 && '["RL8", "RL9"]' || '["RL8"]') }}

    steps:
      - name: Debug
        run: |
          echo test_RL9: ${{ inputs.test_RL9 }}
          echo matrix: ${{ matrix.image }}
