name: test matrix with inputs
'on':
  workflow_dispatch:
    inputs:
      test_RL9:
         required: true
         type: boolean
         default: false
  push: # don't want this for build
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test-job
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: [RL8, RL9]
        rl9_selected:
          - ${{ inputs.test_RL9 == true }} # only potentially true for workflow_dispatch
        rl9_branch:
          - ${{ startsWith(github.head_ref, 'rl9') == true }} # only potentially for pull_request, always false on merge
        exclude:
          - image: RL9
            rl9_selected: false
            rl9_branch: false
          # don't run RL9 on merge to main:
          # is automatically the case for non- 'rl9..' branches
          # a change

    steps:
      - name: Debug
        run: |
          echo test_RL9: ${{ inputs.test_RL9 }}
          echo matrix: ${{ matrix.image }}
          echo github.head_ref: ${{ github.head_ref }}
          echo is rl9: ${{ startsWith(github.head_ref, 'rl9') == true }}
